apiVersion: apps/v1
kind: Deployment
metadata:
  name: jh-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jh-demo-app
  template:
    metadata:
      labels:
        app: jh-demo-app
    spec:
      containers:
        - name: app
          image: huggardj/simple-app:1.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: jh-demo-app
spec:
  selector:
    app: jh-demo-app
  ports:
    - name: "http" 
      port: 80
      targetPort: 8080
  type: LoadBalancer
